from typing import List

def run_mecab_main(argv: List[str] = ...) -> None: ...
def run_mecab_dict_index(argv: List[str] = ...) -> None: ...
def run_mecab_dict_gen(argv: List[str] = ...) -> None: ...
def run_mecab_cost_train(argv: List[str] = ...) -> None: ...
def run_mecab_system_eval(argv: List[str] = ...) -> None: ...
def run_mecab_test_gen(argv: List[str] = ...) -> None: ...
