from typing import List, Optional, Tuple

class Tagger:
    def __init__(self, dic_dir: Optional[str] = ...): ...
    def parse(self, text: str) -> Tuple[Tuple[str, str], ...]: ...

def mecab_main(argv: List[str]) -> None: ...
def mecab_dict_index(argv: List[str]) -> None: ...
def mecab_dict_gen(argv: List[str]) -> None: ...
def mecab_cost_train(argv: List[str]) -> None: ...
def mecab_system_eval(argv: List[str]) -> None: ...
def mecab_test_gen(argv: List[str]) -> None: ...
