from typing import List, Optional

class Tagger:
    def __init__(self, dic_dir: Optional[str] = ...): ...
    def parse(self, text: str) -> str: ...

def mecab_dict_index(argv: List[str]) -> None: ...
def mecab_dict_gen(argv: List[str]) -> None: ...
def mecab_cost_train(argv: List[str]) -> None: ...
